title: OSISMPK SMANIWA
description: Blog OSISMPK SMANIWA
author: Rengga Prakoso Nugroho
github: https://github.com/vzrenggamani
about: Blog resmi dari OSISMPK SMANIWA yang dikelola oleh Sie Bidang TI OSISMPK SMANIWA
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-instagram
      link: "https://instagram.com/osismpksmaniwa"
    - icon: fa-github
      link: "https://github.com/vzrenggamani"

share:
  twitter_username: -
  fb_appid: -

urls:
    - text: Tentang Kita
      url: /about/
    - text: Kegiatan
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://blog.osismpksmaniwa.vzrenggamani.tk"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
